name: Trigger Next Branch Deploy

on:
  push:
    branches: [ next ]

permissions:
  contents: read

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger deploy workflow in mirror repository
      run: |
        gh workflow run deploy \
          --repo Origami74/receipt-cash-next-mirror \
          --ref main
      env:
        GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}